// source: system_message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var model_pb = require('./model_pb.js');
goog.object.extend(proto, model_pb);
var thread_pb = require('./thread_pb.js');
goog.object.extend(proto, thread_pb);
var post_pb = require('./post_pb.js');
goog.object.extend(proto, post_pb);
goog.exportSymbol('proto.model.SystemMessage', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.SystemMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.model.SystemMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.SystemMessage.displayName = 'proto.model.SystemMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.SystemMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.model.SystemMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.SystemMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.SystemMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    model: (f = msg.getModel()) && model_pb.Model.toObject(includeInstance, f),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    body: jspb.Message.getFieldWithDefault(msg, 3, ""),
    canRebuttal: (f = msg.getCanRebuttal()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    hasRebuttal: (f = msg.getHasRebuttal()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    rebuttalRejected: (f = msg.getRebuttalRejected()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    fromThreadId: (f = msg.getFromThreadId()) && google_protobuf_wrappers_pb.UInt64Value.toObject(includeInstance, f),
    fromPostId: (f = msg.getFromPostId()) && google_protobuf_wrappers_pb.UInt64Value.toObject(includeInstance, f),
    fromThread: (f = msg.getFromThread()) && thread_pb.Thread.toObject(includeInstance, f),
    fromPost: (f = msg.getFromPost()) && post_pb.Post.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.SystemMessage}
 */
proto.model.SystemMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.SystemMessage;
  return proto.model.SystemMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.SystemMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.SystemMessage}
 */
proto.model.SystemMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new model_pb.Model;
      reader.readMessage(value,model_pb.Model.deserializeBinaryFromReader);
      msg.setModel(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBody(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setCanRebuttal(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setHasRebuttal(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setRebuttalRejected(value);
      break;
    case 7:
      var value = new google_protobuf_wrappers_pb.UInt64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.UInt64Value.deserializeBinaryFromReader);
      msg.setFromThreadId(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.UInt64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.UInt64Value.deserializeBinaryFromReader);
      msg.setFromPostId(value);
      break;
    case 9:
      var value = new thread_pb.Thread;
      reader.readMessage(value,thread_pb.Thread.deserializeBinaryFromReader);
      msg.setFromThread(value);
      break;
    case 10:
      var value = new post_pb.Post;
      reader.readMessage(value,post_pb.Post.deserializeBinaryFromReader);
      msg.setFromPost(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.SystemMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.SystemMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.SystemMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.SystemMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getModel();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      model_pb.Model.serializeBinaryToWriter
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBody();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCanRebuttal();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getHasRebuttal();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getRebuttalRejected();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getFromThreadId();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_wrappers_pb.UInt64Value.serializeBinaryToWriter
    );
  }
  f = message.getFromPostId();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_wrappers_pb.UInt64Value.serializeBinaryToWriter
    );
  }
  f = message.getFromThread();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      thread_pb.Thread.serializeBinaryToWriter
    );
  }
  f = message.getFromPost();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      post_pb.Post.serializeBinaryToWriter
    );
  }
};


/**
 * optional Model model = 1;
 * @return {?proto.model.Model}
 */
proto.model.SystemMessage.prototype.getModel = function() {
  return /** @type{?proto.model.Model} */ (
    jspb.Message.getWrapperField(this, model_pb.Model, 1));
};


/**
 * @param {?proto.model.Model|undefined} value
 * @return {!proto.model.SystemMessage} returns this
*/
proto.model.SystemMessage.prototype.setModel = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.model.SystemMessage} returns this
 */
proto.model.SystemMessage.prototype.clearModel = function() {
  return this.setModel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.model.SystemMessage.prototype.hasModel = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.model.SystemMessage.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.SystemMessage} returns this
 */
proto.model.SystemMessage.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string body = 3;
 * @return {string}
 */
proto.model.SystemMessage.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.SystemMessage} returns this
 */
proto.model.SystemMessage.prototype.setBody = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.BoolValue can_rebuttal = 4;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.model.SystemMessage.prototype.getCanRebuttal = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 4));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.model.SystemMessage} returns this
*/
proto.model.SystemMessage.prototype.setCanRebuttal = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.model.SystemMessage} returns this
 */
proto.model.SystemMessage.prototype.clearCanRebuttal = function() {
  return this.setCanRebuttal(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.model.SystemMessage.prototype.hasCanRebuttal = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.BoolValue has_rebuttal = 5;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.model.SystemMessage.prototype.getHasRebuttal = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 5));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.model.SystemMessage} returns this
*/
proto.model.SystemMessage.prototype.setHasRebuttal = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.model.SystemMessage} returns this
 */
proto.model.SystemMessage.prototype.clearHasRebuttal = function() {
  return this.setHasRebuttal(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.model.SystemMessage.prototype.hasHasRebuttal = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.BoolValue rebuttal_rejected = 6;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.model.SystemMessage.prototype.getRebuttalRejected = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 6));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.model.SystemMessage} returns this
*/
proto.model.SystemMessage.prototype.setRebuttalRejected = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.model.SystemMessage} returns this
 */
proto.model.SystemMessage.prototype.clearRebuttalRejected = function() {
  return this.setRebuttalRejected(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.model.SystemMessage.prototype.hasRebuttalRejected = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.UInt64Value from_thread_id = 7;
 * @return {?proto.google.protobuf.UInt64Value}
 */
proto.model.SystemMessage.prototype.getFromThreadId = function() {
  return /** @type{?proto.google.protobuf.UInt64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.UInt64Value, 7));
};


/**
 * @param {?proto.google.protobuf.UInt64Value|undefined} value
 * @return {!proto.model.SystemMessage} returns this
*/
proto.model.SystemMessage.prototype.setFromThreadId = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.model.SystemMessage} returns this
 */
proto.model.SystemMessage.prototype.clearFromThreadId = function() {
  return this.setFromThreadId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.model.SystemMessage.prototype.hasFromThreadId = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.UInt64Value from_post_id = 8;
 * @return {?proto.google.protobuf.UInt64Value}
 */
proto.model.SystemMessage.prototype.getFromPostId = function() {
  return /** @type{?proto.google.protobuf.UInt64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.UInt64Value, 8));
};


/**
 * @param {?proto.google.protobuf.UInt64Value|undefined} value
 * @return {!proto.model.SystemMessage} returns this
*/
proto.model.SystemMessage.prototype.setFromPostId = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.model.SystemMessage} returns this
 */
proto.model.SystemMessage.prototype.clearFromPostId = function() {
  return this.setFromPostId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.model.SystemMessage.prototype.hasFromPostId = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional Thread from_thread = 9;
 * @return {?proto.model.Thread}
 */
proto.model.SystemMessage.prototype.getFromThread = function() {
  return /** @type{?proto.model.Thread} */ (
    jspb.Message.getWrapperField(this, thread_pb.Thread, 9));
};


/**
 * @param {?proto.model.Thread|undefined} value
 * @return {!proto.model.SystemMessage} returns this
*/
proto.model.SystemMessage.prototype.setFromThread = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.model.SystemMessage} returns this
 */
proto.model.SystemMessage.prototype.clearFromThread = function() {
  return this.setFromThread(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.model.SystemMessage.prototype.hasFromThread = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional Post from_post = 10;
 * @return {?proto.model.Post}
 */
proto.model.SystemMessage.prototype.getFromPost = function() {
  return /** @type{?proto.model.Post} */ (
    jspb.Message.getWrapperField(this, post_pb.Post, 10));
};


/**
 * @param {?proto.model.Post|undefined} value
 * @return {!proto.model.SystemMessage} returns this
*/
proto.model.SystemMessage.prototype.setFromPost = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.model.SystemMessage} returns this
 */
proto.model.SystemMessage.prototype.clearFromPost = function() {
  return this.setFromPost(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.model.SystemMessage.prototype.hasFromPost = function() {
  return jspb.Message.getField(this, 10) != null;
};


goog.object.extend(exports, proto.model);
